---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-app-secrets
  namespace: argocd
spec:
  encryptedData:
    api-key: AgCEmYQOxjy7UjykuLrDMYy8YMFAHo+nPJoOvgU+wKD72Cj0ANTpkTUoYCU2ZZ/FPZwE9ICCopePVTZ9VpWiiSvAD/o1Evf/vt6F9enL8W+zE43qcp8kAIjf7EUEQcAfmnblCw85eDoMhW50FX3wjQQNEz0eAAf/7HpEEcWqgvLCJyAI7dvScBabV45lynbqRBZDtwpLOedkkEhm6f8Wf1yl+niz4UCj2KbPWyoG/x9HU4VkqGjaE8TpebgnfCzz1UYbWRXjz84Qul9B5DHFp6qSRztqmKUE2YJZY0SC+v3M9PfzTK2TvnhkuWQixQjKw6Y4FP8AeB8M+fWJULffbwjtBnJ/XPz+uCNVrPybIMoyjb+lAXt+6IXGeirN9k24s02nGG5WOstFysWjI4/QU6UGWZSe81RGtIquWH1wob9wwlYOvKuZj9RlGM9+auWHkdBSF98G30+fgJrbW9Hn6qUHBxRB+iQgRnUBUHycoqklEWyx3sHkdogtDMRs0gAZ4tyJAYoK/uy0+SHs1gAckR+RcUYjN5ONmR/T0ChSFZAuRD6Bk0q9s2JTlGUjtEYTQn7jq5+EqXWRdmfV5qPnlVsYGy7zR3SRn3d5zm/o+XH1IC4oTWkx3nfK9yfqdn6D3OwguzyPUpz+S3leNqQKt02e/b81HSTnPzfoS8+6a3f5aSOYedGw2MdSSVvLYIfubRuX4iNox/Y=
    db-password: AgB3BPZXdbMd5T2g8oQapvM+FhWgB3M4phg8BZ9ecBU+fGNywhDpHsL3GlX7RmpRZKLV/S+lN33SSJTXI539dMCTiXrHWDhHmdu3TXcBQTp99wcAWMtqE1XnL4t+NoW4o3zEnyFTGS1CBb1T3WtvBl7lGF/A/hCLsYzTFw7+zkaIwWxDll5YFJaSTvF1aHtSTkRjldqyFTmLd7ZuMU9uP9TC4Bu4hxTWOOtS4Hoqw+r5UgK/IZv+BMKkZKRQh25Qjgaxn1issu8XuUaT/b9UB7DZ4kfXbWNPPIW3zD0Lg42WtVrfgtWEsA6cO1W2klFJZn2B1gR8WWiiz6fvgzXyTw9b8O7bi94XczODh51mA4ZIAGbXVt/XwenCiOglvjABkqJlQLWBR49yqYUpIlbVMNQQ8lnjrMsuAW5wLJmHha3pbDkmDJybm/rMum5ZaBScQeNh0rHlZPTTr5aknqlfZflQ7lpzLQxRAWam7siNkBL4XhTLPIXK53v764L5gdQP0FoCS8UNEDddwt2dodVPWIS8+gVA99IhPomzo0i0ta/cgfjwpDfcYj/tF3nnUBjtWS2zRFmu2upAQkaZmJxjWFybg9veKmZ9Emw93wg7OVrfVjpVgBXnyP8eJKSIR4tZFm04xY+mWviuH50cfJdqzpnh4NrGKklC62xmd2lNgq4U6oId8uecQsQ9dHeVmYS386o3FYnYiEOLaOw=
  template:
    metadata:
      creationTimestamp: null
      name: my-app-secrets
      namespace: argocd
    type: Opaque
